name: Publish to PyPI

on:
  release:
    types: [published]


jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v3
        id: setup-rye
        with:
          enable-cache: true
          working-directory: py
          cache-prefix: ${{ matrix.python-version }}
      - name: Pin python-version ${{ matrix.python-version }}
        working-directory: py
        run: rye pin ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: py
        run: rye sync --no-lock
      - name: Run Tests
        working-directory: py
        run: rye run pytest -v
      - name: Build package
        working-directory: py
        run: rye build
      - name: Publish to PyPI
        working-directory: py
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: rye publish --token $PYPI_TOKEN --yes --skip-existing

